### ISSUE TITLE
Run commands seperately

### ISSUE THREAD

**Issue by Seidenreiher** [anilbeesetti/archcraft_rofi_fix#3]
When I typed `./archcraft_rofi_fix.sh -bspwm -openbox`, nothing changed. I had to run both the `-bspwm` and the `-openbox` command seperately. Now it workes.
Note: There's a little misstake in the README: the Example should be ` ./archcraft_rofi_fix.sh -openbox -bspw`**m** :wink:

**Comment by anilbeesetti** [comment]
Can you send me the output when you run with `./archcraft_rofi_fix.sh -bspwm -openbox`. so that i can examine what happened.

**Comment by anilbeesetti** [comment]
I fixed this issue in new commit
