### ISSUE TITLE
symbols too long (i3)

### ISSUE THREAD

**Issue by Seidenreiher** [anilbeesetti/archcraft_rofi_fix#5]
The white spaces are gone now, but the Symbols still are too long in i3wm.

![Screenshot_2021-09-22-02_1920x1080](https://user-images.githubusercontent.com/91087407/134704104-0fa036a4-ef6b-48f0-b37b-e8656c2aa1f4.png)
![Screenshot_2021-09-22-38_1920x1080](https://user-images.githubusercontent.com/91087407/134704107-ae9e28d2-31f4-4d6e-85a8-cb88b4b5e659.png)
![Screenshot_2021-09-22-42_1920x1080](https://user-images.githubusercontent.com/91087407/134704111-0ba97c61-ca6d-4c66-bceb-577e5e903049.png)

**Comment by anilbeesetti** [comment]
use the latest release of archcraft os
